[build]
builder = "nixpacks"
buildCommand = "npm ci --omit=dev && npm run build"
watchPatterns = ["package.json", "package-lock.json", "src/**/*.ts", "tsconfig.json"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
